---
- name: ensure kuberenetes is installed
  pip:
    name: kubernetes
    state: present

- name: ensure namespace is created
  k8s:
    name: hello-world
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"

- name: deploy hello-world app
  k8s:
    state: present
    definition: "{{ lookup('file', '../kubernetes/app-deployment.yaml') }}"
    kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
