---
- name: Destroy everything
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
  - name: Delete kube config file locally
    file:
      path: "{{ lookup('env', 'HOME') }}/.kube/config"
      state: absent

  - name: Destroy cluster
    azure_rm_aks:
      name: "{{ cluster_name }}"
      resource_group: "{{ resource_group }}"
      state: absent

  - name: Destroy resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      state: absent